working_dir: ./testdata/tmp/
github_configs:
  - token_envvar_name: GITHUB_TOKEN
    repo_configs:
      - owner: kobtea
        regex: jsonnet
        conftest_configs:
          - target: repo
            policies:
              - ./example/policy/github_repo.rego
          - target: src
            input: .github/workflows
            combine: false
            policies:
              - ./example/policy/github_actions.rego
      - owner: kobtea
        regex: exporter
        conftest_configs:
          - target: repo
            policies:
              - ./example/policy/github_repo.rego
      - owner: prometheus
        regex: node_exporter
        conftest_configs:
          - target: repo
            policies:
              - ./example/policy/github_repo.rego
