version: 2
before:
  hooks:
    - go mod tidy
builds:
  - flags: -a -tags netgo
    ldflags:
      - -s -w
      - -X github.com/kobtea/gorgo/cmd.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: arm
        goarm: 7
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^cut:'
      - '^typo'
dockers_v2:
  - images:
      - ghcr.io/kobtea/gorgo
    tags:
      - "latest"
      - "v{{ .Version }}"
    platforms:
      - linux/amd64
      - linux/arm64
