name: ci

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

env:
  CGO_ENABLED: 0

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1
          args: -E gofmt,goimports --timeout 5m0s

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - name: Test
        run: make test
      - name: Build
        run: make build

  tagging:
    name: tagging
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - lint
      - build
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
      - uses: kobtea/release-tag-action@v0
