name: ci

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

env:
  CGO_ENABLED: 0

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1
          args: -E gofmt,goimports

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - name: Test
        run: make test
      - name: Build
        run: make build
